//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ABCLogisticModel", "FK_CangVanChuyen_QuocGia", "QuocGia", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QuanLyKhachHang.DA.QuocGia), "CangVanChuyen", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(QuanLyKhachHang.DA.CangVanChuyen), true)]
[assembly: EdmRelationshipAttribute("ABCLogisticModel", "FK_KhachHang_NhanVien", "NhanVien", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(QuanLyKhachHang.DA.NhanVien), "KhachHang", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QuanLyKhachHang.DA.KhachHang), true)]
[assembly: EdmRelationshipAttribute("ABCLogisticModel", "FK_NhanVien_PhongBan", "PhongBan", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(QuanLyKhachHang.DA.PhongBan), "NhanVien", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QuanLyKhachHang.DA.NhanVien), true)]
[assembly: EdmRelationshipAttribute("ABCLogisticModel", "FK_TinhThanh_QuocGia1", "QuocGia", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(QuanLyKhachHang.DA.QuocGia), "TinhThanh", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QuanLyKhachHang.DA.TinhThanh), true)]

#endregion

namespace QuanLyKhachHang.DA
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ABCLogisticEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ABCLogisticEntities1 object using the connection string found in the 'ABCLogisticEntities1' section of the application configuration file.
        /// </summary>
        public ABCLogisticEntities1() : base("name=ABCLogisticEntities1", "ABCLogisticEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ABCLogisticEntities1 object.
        /// </summary>
        public ABCLogisticEntities1(string connectionString) : base(connectionString, "ABCLogisticEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ABCLogisticEntities1 object.
        /// </summary>
        public ABCLogisticEntities1(EntityConnection connection) : base(connection, "ABCLogisticEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CangVanChuyen> CangVanChuyens
        {
            get
            {
                if ((_CangVanChuyens == null))
                {
                    _CangVanChuyens = base.CreateObjectSet<CangVanChuyen>("CangVanChuyens");
                }
                return _CangVanChuyens;
            }
        }
        private ObjectSet<CangVanChuyen> _CangVanChuyens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Container> Containers
        {
            get
            {
                if ((_Containers == null))
                {
                    _Containers = base.CreateObjectSet<Container>("Containers");
                }
                return _Containers;
            }
        }
        private ObjectSet<Container> _Containers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KhachHang> KhachHangs
        {
            get
            {
                if ((_KhachHangs == null))
                {
                    _KhachHangs = base.CreateObjectSet<KhachHang>("KhachHangs");
                }
                return _KhachHangs;
            }
        }
        private ObjectSet<KhachHang> _KhachHangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LinhVucKinhDoanh> LinhVucKinhDoanhs
        {
            get
            {
                if ((_LinhVucKinhDoanhs == null))
                {
                    _LinhVucKinhDoanhs = base.CreateObjectSet<LinhVucKinhDoanh>("LinhVucKinhDoanhs");
                }
                return _LinhVucKinhDoanhs;
            }
        }
        private ObjectSet<LinhVucKinhDoanh> _LinhVucKinhDoanhs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NgoaiTe> NgoaiTes
        {
            get
            {
                if ((_NgoaiTes == null))
                {
                    _NgoaiTes = base.CreateObjectSet<NgoaiTe>("NgoaiTes");
                }
                return _NgoaiTes;
            }
        }
        private ObjectSet<NgoaiTe> _NgoaiTes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NhanVien> NhanViens
        {
            get
            {
                if ((_NhanViens == null))
                {
                    _NhanViens = base.CreateObjectSet<NhanVien>("NhanViens");
                }
                return _NhanViens;
            }
        }
        private ObjectSet<NhanVien> _NhanViens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PhongBan> PhongBans
        {
            get
            {
                if ((_PhongBans == null))
                {
                    _PhongBans = base.CreateObjectSet<PhongBan>("PhongBans");
                }
                return _PhongBans;
            }
        }
        private ObjectSet<PhongBan> _PhongBans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QuocGia> QuocGias
        {
            get
            {
                if ((_QuocGias == null))
                {
                    _QuocGias = base.CreateObjectSet<QuocGia>("QuocGias");
                }
                return _QuocGias;
            }
        }
        private ObjectSet<QuocGia> _QuocGias;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TinhThanh> TinhThanhs
        {
            get
            {
                if ((_TinhThanhs == null))
                {
                    _TinhThanhs = base.CreateObjectSet<TinhThanh>("TinhThanhs");
                }
                return _TinhThanhs;
            }
        }
        private ObjectSet<TinhThanh> _TinhThanhs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CangVanChuyens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCangVanChuyens(CangVanChuyen cangVanChuyen)
        {
            base.AddObject("CangVanChuyens", cangVanChuyen);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Containers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContainers(Container container)
        {
            base.AddObject("Containers", container);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KhachHangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKhachHangs(KhachHang khachHang)
        {
            base.AddObject("KhachHangs", khachHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LinhVucKinhDoanhs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLinhVucKinhDoanhs(LinhVucKinhDoanh linhVucKinhDoanh)
        {
            base.AddObject("LinhVucKinhDoanhs", linhVucKinhDoanh);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NgoaiTes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNgoaiTes(NgoaiTe ngoaiTe)
        {
            base.AddObject("NgoaiTes", ngoaiTe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NhanViens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNhanViens(NhanVien nhanVien)
        {
            base.AddObject("NhanViens", nhanVien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PhongBans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhongBans(PhongBan phongBan)
        {
            base.AddObject("PhongBans", phongBan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QuocGias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuocGias(QuocGia quocGia)
        {
            base.AddObject("QuocGias", quocGia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TinhThanhs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTinhThanhs(TinhThanh tinhThanh)
        {
            base.AddObject("TinhThanhs", tinhThanh);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticModel", Name="CangVanChuyen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CangVanChuyen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CangVanChuyen object.
        /// </summary>
        /// <param name="maCang">Initial value of the MaCang property.</param>
        public static CangVanChuyen CreateCangVanChuyen(global::System.Int32 maCang)
        {
            CangVanChuyen cangVanChuyen = new CangVanChuyen();
            cangVanChuyen.MaCang = maCang;
            return cangVanChuyen;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaCang
        {
            get
            {
                return _MaCang;
            }
            set
            {
                if (_MaCang != value)
                {
                    OnMaCangChanging(value);
                    ReportPropertyChanging("MaCang");
                    _MaCang = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaCang");
                    OnMaCangChanged();
                }
            }
        }
        private global::System.Int32 _MaCang;
        partial void OnMaCangChanging(global::System.Int32 value);
        partial void OnMaCangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tencang
        {
            get
            {
                return _Tencang;
            }
            set
            {
                OnTencangChanging(value);
                ReportPropertyChanging("Tencang");
                _Tencang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tencang");
                OnTencangChanged();
            }
        }
        private global::System.String _Tencang;
        partial void OnTencangChanging(global::System.String value);
        partial void OnTencangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sdt
        {
            get
            {
                return _Sdt;
            }
            set
            {
                OnSdtChanging(value);
                ReportPropertyChanging("Sdt");
                _Sdt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sdt");
                OnSdtChanged();
            }
        }
        private Nullable<global::System.Int32> _Sdt;
        partial void OnSdtChanging(Nullable<global::System.Int32> value);
        partial void OnSdtChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ABCLogisticModel", "FK_CangVanChuyen_QuocGia", "QuocGia")]
        public QuocGia QuocGia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuocGia>("ABCLogisticModel.FK_CangVanChuyen_QuocGia", "QuocGia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuocGia>("ABCLogisticModel.FK_CangVanChuyen_QuocGia", "QuocGia").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<QuocGia> QuocGiaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuocGia>("ABCLogisticModel.FK_CangVanChuyen_QuocGia", "QuocGia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<QuocGia>("ABCLogisticModel.FK_CangVanChuyen_QuocGia", "QuocGia", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticModel", Name="Container")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Container : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Container object.
        /// </summary>
        /// <param name="maContainer">Initial value of the MaContainer property.</param>
        public static Container CreateContainer(global::System.String maContainer)
        {
            Container container = new Container();
            container.MaContainer = maContainer;
            return container;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaContainer
        {
            get
            {
                return _MaContainer;
            }
            set
            {
                if (_MaContainer != value)
                {
                    OnMaContainerChanging(value);
                    ReportPropertyChanging("MaContainer");
                    _MaContainer = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaContainer");
                    OnMaContainerChanged();
                }
            }
        }
        private global::System.String _MaContainer;
        partial void OnMaContainerChanging(global::System.String value);
        partial void OnMaContainerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenContainer
        {
            get
            {
                return _TenContainer;
            }
            set
            {
                OnTenContainerChanging(value);
                ReportPropertyChanging("TenContainer");
                _TenContainer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenContainer");
                OnTenContainerChanged();
            }
        }
        private global::System.String _TenContainer;
        partial void OnTenContainerChanging(global::System.String value);
        partial void OnTenContainerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MoTa
        {
            get
            {
                return _MoTa;
            }
            set
            {
                OnMoTaChanging(value);
                ReportPropertyChanging("MoTa");
                _MoTa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MoTa");
                OnMoTaChanged();
            }
        }
        private global::System.String _MoTa;
        partial void OnMoTaChanging(global::System.String value);
        partial void OnMoTaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticModel", Name="KhachHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KhachHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KhachHang object.
        /// </summary>
        /// <param name="maCongTy">Initial value of the MaCongTy property.</param>
        public static KhachHang CreateKhachHang(global::System.String maCongTy)
        {
            KhachHang khachHang = new KhachHang();
            khachHang.MaCongTy = maCongTy;
            return khachHang;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaCongTy
        {
            get
            {
                return _MaCongTy;
            }
            set
            {
                if (_MaCongTy != value)
                {
                    OnMaCongTyChanging(value);
                    ReportPropertyChanging("MaCongTy");
                    _MaCongTy = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaCongTy");
                    OnMaCongTyChanged();
                }
            }
        }
        private global::System.String _MaCongTy;
        partial void OnMaCongTyChanging(global::System.String value);
        partial void OnMaCongTyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenCTyV
        {
            get
            {
                return _TenCTyV;
            }
            set
            {
                OnTenCTyVChanging(value);
                ReportPropertyChanging("TenCTyV");
                _TenCTyV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenCTyV");
                OnTenCTyVChanged();
            }
        }
        private global::System.String _TenCTyV;
        partial void OnTenCTyVChanging(global::System.String value);
        partial void OnTenCTyVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenCTyE
        {
            get
            {
                return _TenCTyE;
            }
            set
            {
                OnTenCTyEChanging(value);
                ReportPropertyChanging("TenCTyE");
                _TenCTyE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenCTyE");
                OnTenCTyEChanged();
            }
        }
        private global::System.String _TenCTyE;
        partial void OnTenCTyEChanging(global::System.String value);
        partial void OnTenCTyEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenCTyVietTat
        {
            get
            {
                return _TenCTyVietTat;
            }
            set
            {
                OnTenCTyVietTatChanging(value);
                ReportPropertyChanging("TenCTyVietTat");
                _TenCTyVietTat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenCTyVietTat");
                OnTenCTyVietTatChanged();
            }
        }
        private global::System.String _TenCTyVietTat;
        partial void OnTenCTyVietTatChanging(global::System.String value);
        partial void OnTenCTyVietTatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LinhVucKinhDoanh
        {
            get
            {
                return _LinhVucKinhDoanh;
            }
            set
            {
                OnLinhVucKinhDoanhChanging(value);
                ReportPropertyChanging("LinhVucKinhDoanh");
                _LinhVucKinhDoanh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LinhVucKinhDoanh");
                OnLinhVucKinhDoanhChanged();
            }
        }
        private global::System.String _LinhVucKinhDoanh;
        partial void OnLinhVucKinhDoanhChanging(global::System.String value);
        partial void OnLinhVucKinhDoanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenQuocGia
        {
            get
            {
                return _TenQuocGia;
            }
            set
            {
                OnTenQuocGiaChanging(value);
                ReportPropertyChanging("TenQuocGia");
                _TenQuocGia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenQuocGia");
                OnTenQuocGiaChanged();
            }
        }
        private global::System.String _TenQuocGia;
        partial void OnTenQuocGiaChanging(global::System.String value);
        partial void OnTenQuocGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TinhThanh
        {
            get
            {
                return _TinhThanh;
            }
            set
            {
                OnTinhThanhChanging(value);
                ReportPropertyChanging("TinhThanh");
                _TinhThanh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TinhThanh");
                OnTinhThanhChanged();
            }
        }
        private global::System.String _TinhThanh;
        partial void OnTinhThanhChanging(global::System.String value);
        partial void OnTinhThanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sdt
        {
            get
            {
                return _Sdt;
            }
            set
            {
                OnSdtChanging(value);
                ReportPropertyChanging("Sdt");
                _Sdt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sdt");
                OnSdtChanged();
            }
        }
        private global::System.String _Sdt;
        partial void OnSdtChanging(global::System.String value);
        partial void OnSdtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private global::System.String _Fax;
        partial void OnFaxChanging(global::System.String value);
        partial void OnFaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Web
        {
            get
            {
                return _Web;
            }
            set
            {
                OnWebChanging(value);
                ReportPropertyChanging("Web");
                _Web = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Web");
                OnWebChanged();
            }
        }
        private global::System.String _Web;
        partial void OnWebChanging(global::System.String value);
        partial void OnWebChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaNhanVien
        {
            get
            {
                return _MaNhanVien;
            }
            set
            {
                OnMaNhanVienChanging(value);
                ReportPropertyChanging("MaNhanVien");
                _MaNhanVien = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaNhanVien");
                OnMaNhanVienChanged();
            }
        }
        private global::System.String _MaNhanVien;
        partial void OnMaNhanVienChanging(global::System.String value);
        partial void OnMaNhanVienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CongTyChuQuan
        {
            get
            {
                return _CongTyChuQuan;
            }
            set
            {
                OnCongTyChuQuanChanging(value);
                ReportPropertyChanging("CongTyChuQuan");
                _CongTyChuQuan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CongTyChuQuan");
                OnCongTyChuQuanChanged();
            }
        }
        private global::System.String _CongTyChuQuan;
        partial void OnCongTyChuQuanChanging(global::System.String value);
        partial void OnCongTyChuQuanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoaiKhachHang
        {
            get
            {
                return _LoaiKhachHang;
            }
            set
            {
                OnLoaiKhachHangChanging(value);
                ReportPropertyChanging("LoaiKhachHang");
                _LoaiKhachHang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LoaiKhachHang");
                OnLoaiKhachHangChanged();
            }
        }
        private global::System.String _LoaiKhachHang;
        partial void OnLoaiKhachHangChanging(global::System.String value);
        partial void OnLoaiKhachHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NhanVienQuanLy
        {
            get
            {
                return _NhanVienQuanLy;
            }
            set
            {
                OnNhanVienQuanLyChanging(value);
                ReportPropertyChanging("NhanVienQuanLy");
                _NhanVienQuanLy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NhanVienQuanLy");
                OnNhanVienQuanLyChanged();
            }
        }
        private global::System.String _NhanVienQuanLy;
        partial void OnNhanVienQuanLyChanging(global::System.String value);
        partial void OnNhanVienQuanLyChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ABCLogisticModel", "FK_KhachHang_NhanVien", "NhanVien")]
        public NhanVien NhanVien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhanVien>("ABCLogisticModel.FK_KhachHang_NhanVien", "NhanVien").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhanVien>("ABCLogisticModel.FK_KhachHang_NhanVien", "NhanVien").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NhanVien> NhanVienReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhanVien>("ABCLogisticModel.FK_KhachHang_NhanVien", "NhanVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NhanVien>("ABCLogisticModel.FK_KhachHang_NhanVien", "NhanVien", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticModel", Name="LinhVucKinhDoanh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LinhVucKinhDoanh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LinhVucKinhDoanh object.
        /// </summary>
        /// <param name="maLinhVucKinhDoanh">Initial value of the MaLinhVucKinhDoanh property.</param>
        public static LinhVucKinhDoanh CreateLinhVucKinhDoanh(global::System.String maLinhVucKinhDoanh)
        {
            LinhVucKinhDoanh linhVucKinhDoanh = new LinhVucKinhDoanh();
            linhVucKinhDoanh.MaLinhVucKinhDoanh = maLinhVucKinhDoanh;
            return linhVucKinhDoanh;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaLinhVucKinhDoanh
        {
            get
            {
                return _MaLinhVucKinhDoanh;
            }
            set
            {
                if (_MaLinhVucKinhDoanh != value)
                {
                    OnMaLinhVucKinhDoanhChanging(value);
                    ReportPropertyChanging("MaLinhVucKinhDoanh");
                    _MaLinhVucKinhDoanh = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaLinhVucKinhDoanh");
                    OnMaLinhVucKinhDoanhChanged();
                }
            }
        }
        private global::System.String _MaLinhVucKinhDoanh;
        partial void OnMaLinhVucKinhDoanhChanging(global::System.String value);
        partial void OnMaLinhVucKinhDoanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenLinhVucKinhDoanh
        {
            get
            {
                return _TenLinhVucKinhDoanh;
            }
            set
            {
                OnTenLinhVucKinhDoanhChanging(value);
                ReportPropertyChanging("TenLinhVucKinhDoanh");
                _TenLinhVucKinhDoanh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenLinhVucKinhDoanh");
                OnTenLinhVucKinhDoanhChanged();
            }
        }
        private global::System.String _TenLinhVucKinhDoanh;
        partial void OnTenLinhVucKinhDoanhChanging(global::System.String value);
        partial void OnTenLinhVucKinhDoanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GhiChu
        {
            get
            {
                return _GhiChu;
            }
            set
            {
                OnGhiChuChanging(value);
                ReportPropertyChanging("GhiChu");
                _GhiChu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GhiChu");
                OnGhiChuChanged();
            }
        }
        private global::System.String _GhiChu;
        partial void OnGhiChuChanging(global::System.String value);
        partial void OnGhiChuChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticModel", Name="NgoaiTe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NgoaiTe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NgoaiTe object.
        /// </summary>
        /// <param name="maNgoaiTe">Initial value of the MaNgoaiTe property.</param>
        public static NgoaiTe CreateNgoaiTe(global::System.String maNgoaiTe)
        {
            NgoaiTe ngoaiTe = new NgoaiTe();
            ngoaiTe.MaNgoaiTe = maNgoaiTe;
            return ngoaiTe;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaNgoaiTe
        {
            get
            {
                return _MaNgoaiTe;
            }
            set
            {
                if (_MaNgoaiTe != value)
                {
                    OnMaNgoaiTeChanging(value);
                    ReportPropertyChanging("MaNgoaiTe");
                    _MaNgoaiTe = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaNgoaiTe");
                    OnMaNgoaiTeChanged();
                }
            }
        }
        private global::System.String _MaNgoaiTe;
        partial void OnMaNgoaiTeChanging(global::System.String value);
        partial void OnMaNgoaiTeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenNgoaiTe
        {
            get
            {
                return _TenNgoaiTe;
            }
            set
            {
                OnTenNgoaiTeChanging(value);
                ReportPropertyChanging("TenNgoaiTe");
                _TenNgoaiTe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenNgoaiTe");
                OnTenNgoaiTeChanged();
            }
        }
        private global::System.String _TenNgoaiTe;
        partial void OnTenNgoaiTeChanging(global::System.String value);
        partial void OnTenNgoaiTeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mota
        {
            get
            {
                return _Mota;
            }
            set
            {
                OnMotaChanging(value);
                ReportPropertyChanging("Mota");
                _Mota = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mota");
                OnMotaChanged();
            }
        }
        private global::System.String _Mota;
        partial void OnMotaChanging(global::System.String value);
        partial void OnMotaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticModel", Name="NhanVien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NhanVien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NhanVien object.
        /// </summary>
        /// <param name="maNhanVien">Initial value of the MaNhanVien property.</param>
        public static NhanVien CreateNhanVien(global::System.String maNhanVien)
        {
            NhanVien nhanVien = new NhanVien();
            nhanVien.MaNhanVien = maNhanVien;
            return nhanVien;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaNhanVien
        {
            get
            {
                return _MaNhanVien;
            }
            set
            {
                if (_MaNhanVien != value)
                {
                    OnMaNhanVienChanging(value);
                    ReportPropertyChanging("MaNhanVien");
                    _MaNhanVien = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaNhanVien");
                    OnMaNhanVienChanged();
                }
            }
        }
        private global::System.String _MaNhanVien;
        partial void OnMaNhanVienChanging(global::System.String value);
        partial void OnMaNhanVienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoTen
        {
            get
            {
                return _HoTen;
            }
            set
            {
                OnHoTenChanging(value);
                ReportPropertyChanging("HoTen");
                _HoTen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HoTen");
                OnHoTenChanged();
            }
        }
        private global::System.String _HoTen;
        partial void OnHoTenChanging(global::System.String value);
        partial void OnHoTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NickName
        {
            get
            {
                return _NickName;
            }
            set
            {
                OnNickNameChanging(value);
                ReportPropertyChanging("NickName");
                _NickName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NickName");
                OnNickNameChanged();
            }
        }
        private global::System.String _NickName;
        partial void OnNickNameChanging(global::System.String value);
        partial void OnNickNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GioiTinh
        {
            get
            {
                return _GioiTinh;
            }
            set
            {
                OnGioiTinhChanging(value);
                ReportPropertyChanging("GioiTinh");
                _GioiTinh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GioiTinh");
                OnGioiTinhChanged();
            }
        }
        private global::System.String _GioiTinh;
        partial void OnGioiTinhChanging(global::System.String value);
        partial void OnGioiTinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgaySinh
        {
            get
            {
                return _NgaySinh;
            }
            set
            {
                OnNgaySinhChanging(value);
                ReportPropertyChanging("NgaySinh");
                _NgaySinh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgaySinh");
                OnNgaySinhChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgaySinh;
        partial void OnNgaySinhChanging(Nullable<global::System.DateTime> value);
        partial void OnNgaySinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sdt
        {
            get
            {
                return _Sdt;
            }
            set
            {
                OnSdtChanging(value);
                ReportPropertyChanging("Sdt");
                _Sdt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sdt");
                OnSdtChanged();
            }
        }
        private global::System.String _Sdt;
        partial void OnSdtChanging(global::System.String value);
        partial void OnSdtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TendangNhap
        {
            get
            {
                return _TendangNhap;
            }
            set
            {
                OnTendangNhapChanging(value);
                ReportPropertyChanging("TendangNhap");
                _TendangNhap = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TendangNhap");
                OnTendangNhapChanged();
            }
        }
        private global::System.String _TendangNhap;
        partial void OnTendangNhapChanging(global::System.String value);
        partial void OnTendangNhapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MatKhauDangNhap
        {
            get
            {
                return _MatKhauDangNhap;
            }
            set
            {
                OnMatKhauDangNhapChanging(value);
                ReportPropertyChanging("MatKhauDangNhap");
                _MatKhauDangNhap = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MatKhauDangNhap");
                OnMatKhauDangNhapChanged();
            }
        }
        private global::System.String _MatKhauDangNhap;
        partial void OnMatKhauDangNhapChanging(global::System.String value);
        partial void OnMatKhauDangNhapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Luong
        {
            get
            {
                return _Luong;
            }
            set
            {
                OnLuongChanging(value);
                ReportPropertyChanging("Luong");
                _Luong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Luong");
                OnLuongChanged();
            }
        }
        private Nullable<global::System.Double> _Luong;
        partial void OnLuongChanging(Nullable<global::System.Double> value);
        partial void OnLuongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaPhongBan
        {
            get
            {
                return _MaPhongBan;
            }
            set
            {
                OnMaPhongBanChanging(value);
                ReportPropertyChanging("MaPhongBan");
                _MaPhongBan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaPhongBan");
                OnMaPhongBanChanged();
            }
        }
        private global::System.String _MaPhongBan;
        partial void OnMaPhongBanChanging(global::System.String value);
        partial void OnMaPhongBanChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ABCLogisticModel", "FK_KhachHang_NhanVien", "KhachHang")]
        public EntityCollection<KhachHang> KhachHangs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<KhachHang>("ABCLogisticModel.FK_KhachHang_NhanVien", "KhachHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<KhachHang>("ABCLogisticModel.FK_KhachHang_NhanVien", "KhachHang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ABCLogisticModel", "FK_NhanVien_PhongBan", "PhongBan")]
        public PhongBan PhongBan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhongBan>("ABCLogisticModel.FK_NhanVien_PhongBan", "PhongBan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhongBan>("ABCLogisticModel.FK_NhanVien_PhongBan", "PhongBan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PhongBan> PhongBanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhongBan>("ABCLogisticModel.FK_NhanVien_PhongBan", "PhongBan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PhongBan>("ABCLogisticModel.FK_NhanVien_PhongBan", "PhongBan", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticModel", Name="PhongBan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhongBan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PhongBan object.
        /// </summary>
        /// <param name="maPhongBan">Initial value of the MaPhongBan property.</param>
        public static PhongBan CreatePhongBan(global::System.String maPhongBan)
        {
            PhongBan phongBan = new PhongBan();
            phongBan.MaPhongBan = maPhongBan;
            return phongBan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaPhongBan
        {
            get
            {
                return _MaPhongBan;
            }
            set
            {
                if (_MaPhongBan != value)
                {
                    OnMaPhongBanChanging(value);
                    ReportPropertyChanging("MaPhongBan");
                    _MaPhongBan = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaPhongBan");
                    OnMaPhongBanChanged();
                }
            }
        }
        private global::System.String _MaPhongBan;
        partial void OnMaPhongBanChanging(global::System.String value);
        partial void OnMaPhongBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenPhongban
        {
            get
            {
                return _TenPhongban;
            }
            set
            {
                OnTenPhongbanChanging(value);
                ReportPropertyChanging("TenPhongban");
                _TenPhongban = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenPhongban");
                OnTenPhongbanChanged();
            }
        }
        private global::System.String _TenPhongban;
        partial void OnTenPhongbanChanging(global::System.String value);
        partial void OnTenPhongbanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ABCLogisticModel", "FK_NhanVien_PhongBan", "NhanVien")]
        public EntityCollection<NhanVien> NhanViens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NhanVien>("ABCLogisticModel.FK_NhanVien_PhongBan", "NhanVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NhanVien>("ABCLogisticModel.FK_NhanVien_PhongBan", "NhanVien", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticModel", Name="QuocGia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QuocGia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QuocGia object.
        /// </summary>
        /// <param name="maQuocGia">Initial value of the MaQuocGia property.</param>
        public static QuocGia CreateQuocGia(global::System.Int32 maQuocGia)
        {
            QuocGia quocGia = new QuocGia();
            quocGia.MaQuocGia = maQuocGia;
            return quocGia;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaQuocGia
        {
            get
            {
                return _MaQuocGia;
            }
            set
            {
                if (_MaQuocGia != value)
                {
                    OnMaQuocGiaChanging(value);
                    ReportPropertyChanging("MaQuocGia");
                    _MaQuocGia = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaQuocGia");
                    OnMaQuocGiaChanged();
                }
            }
        }
        private global::System.Int32 _MaQuocGia;
        partial void OnMaQuocGiaChanging(global::System.Int32 value);
        partial void OnMaQuocGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenQuocGia
        {
            get
            {
                return _TenQuocGia;
            }
            set
            {
                OnTenQuocGiaChanging(value);
                ReportPropertyChanging("TenQuocGia");
                _TenQuocGia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenQuocGia");
                OnTenQuocGiaChanged();
            }
        }
        private global::System.String _TenQuocGia;
        partial void OnTenQuocGiaChanging(global::System.String value);
        partial void OnTenQuocGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GhiChu
        {
            get
            {
                return _GhiChu;
            }
            set
            {
                OnGhiChuChanging(value);
                ReportPropertyChanging("GhiChu");
                _GhiChu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GhiChu");
                OnGhiChuChanged();
            }
        }
        private global::System.String _GhiChu;
        partial void OnGhiChuChanging(global::System.String value);
        partial void OnGhiChuChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ABCLogisticModel", "FK_CangVanChuyen_QuocGia", "CangVanChuyen")]
        public CangVanChuyen CangVanChuyen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CangVanChuyen>("ABCLogisticModel.FK_CangVanChuyen_QuocGia", "CangVanChuyen").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CangVanChuyen>("ABCLogisticModel.FK_CangVanChuyen_QuocGia", "CangVanChuyen").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CangVanChuyen> CangVanChuyenReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CangVanChuyen>("ABCLogisticModel.FK_CangVanChuyen_QuocGia", "CangVanChuyen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CangVanChuyen>("ABCLogisticModel.FK_CangVanChuyen_QuocGia", "CangVanChuyen", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ABCLogisticModel", "FK_TinhThanh_QuocGia1", "TinhThanh")]
        public EntityCollection<TinhThanh> TinhThanhs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TinhThanh>("ABCLogisticModel.FK_TinhThanh_QuocGia1", "TinhThanh");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TinhThanh>("ABCLogisticModel.FK_TinhThanh_QuocGia1", "TinhThanh", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticModel", Name="TinhThanh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TinhThanh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TinhThanh object.
        /// </summary>
        /// <param name="maTinhThanh">Initial value of the MaTinhThanh property.</param>
        public static TinhThanh CreateTinhThanh(global::System.String maTinhThanh)
        {
            TinhThanh tinhThanh = new TinhThanh();
            tinhThanh.MaTinhThanh = maTinhThanh;
            return tinhThanh;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaTinhThanh
        {
            get
            {
                return _MaTinhThanh;
            }
            set
            {
                if (_MaTinhThanh != value)
                {
                    OnMaTinhThanhChanging(value);
                    ReportPropertyChanging("MaTinhThanh");
                    _MaTinhThanh = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaTinhThanh");
                    OnMaTinhThanhChanged();
                }
            }
        }
        private global::System.String _MaTinhThanh;
        partial void OnMaTinhThanhChanging(global::System.String value);
        partial void OnMaTinhThanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenTinhThanh
        {
            get
            {
                return _TenTinhThanh;
            }
            set
            {
                OnTenTinhThanhChanging(value);
                ReportPropertyChanging("TenTinhThanh");
                _TenTinhThanh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenTinhThanh");
                OnTenTinhThanhChanged();
            }
        }
        private global::System.String _TenTinhThanh;
        partial void OnTenTinhThanhChanging(global::System.String value);
        partial void OnTenTinhThanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaQuocGia
        {
            get
            {
                return _MaQuocGia;
            }
            set
            {
                OnMaQuocGiaChanging(value);
                ReportPropertyChanging("MaQuocGia");
                _MaQuocGia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaQuocGia");
                OnMaQuocGiaChanged();
            }
        }
        private Nullable<global::System.Int32> _MaQuocGia;
        partial void OnMaQuocGiaChanging(Nullable<global::System.Int32> value);
        partial void OnMaQuocGiaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ABCLogisticModel", "FK_TinhThanh_QuocGia1", "QuocGia")]
        public QuocGia QuocGia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuocGia>("ABCLogisticModel.FK_TinhThanh_QuocGia1", "QuocGia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuocGia>("ABCLogisticModel.FK_TinhThanh_QuocGia1", "QuocGia").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<QuocGia> QuocGiaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuocGia>("ABCLogisticModel.FK_TinhThanh_QuocGia1", "QuocGia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<QuocGia>("ABCLogisticModel.FK_TinhThanh_QuocGia1", "QuocGia", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
