//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace QuanLyKhachHang.DA
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ABCLogisticsEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ABCLogisticsEntities2 object using the connection string found in the 'ABCLogisticsEntities2' section of the application configuration file.
        /// </summary>
        public ABCLogisticsEntities2() : base("name=ABCLogisticsEntities2", "ABCLogisticsEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ABCLogisticsEntities2 object.
        /// </summary>
        public ABCLogisticsEntities2(string connectionString) : base(connectionString, "ABCLogisticsEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ABCLogisticsEntities2 object.
        /// </summary>
        public ABCLogisticsEntities2(EntityConnection connection) : base(connection, "ABCLogisticsEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LinhVucKinhDoanh> LinhVucKinhDoanhs
        {
            get
            {
                if ((_LinhVucKinhDoanhs == null))
                {
                    _LinhVucKinhDoanhs = base.CreateObjectSet<LinhVucKinhDoanh>("LinhVucKinhDoanhs");
                }
                return _LinhVucKinhDoanhs;
            }
        }
        private ObjectSet<LinhVucKinhDoanh> _LinhVucKinhDoanhs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NhanVien> NhanViens
        {
            get
            {
                if ((_NhanViens == null))
                {
                    _NhanViens = base.CreateObjectSet<NhanVien>("NhanViens");
                }
                return _NhanViens;
            }
        }
        private ObjectSet<NhanVien> _NhanViens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QuocGia> QuocGias
        {
            get
            {
                if ((_QuocGias == null))
                {
                    _QuocGias = base.CreateObjectSet<QuocGia>("QuocGias");
                }
                return _QuocGias;
            }
        }
        private ObjectSet<QuocGia> _QuocGias;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TinhThanh> TinhThanhs
        {
            get
            {
                if ((_TinhThanhs == null))
                {
                    _TinhThanhs = base.CreateObjectSet<TinhThanh>("TinhThanhs");
                }
                return _TinhThanhs;
            }
        }
        private ObjectSet<TinhThanh> _TinhThanhs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DanhMucNgoaiTe> DanhMucNgoaiTes
        {
            get
            {
                if ((_DanhMucNgoaiTes == null))
                {
                    _DanhMucNgoaiTes = base.CreateObjectSet<DanhMucNgoaiTe>("DanhMucNgoaiTes");
                }
                return _DanhMucNgoaiTes;
            }
        }
        private ObjectSet<DanhMucNgoaiTe> _DanhMucNgoaiTes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NguoiLienHe> NguoiLienHes
        {
            get
            {
                if ((_NguoiLienHes == null))
                {
                    _NguoiLienHes = base.CreateObjectSet<NguoiLienHe>("NguoiLienHes");
                }
                return _NguoiLienHes;
            }
        }
        private ObjectSet<NguoiLienHe> _NguoiLienHes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LinhVucKinhDoanhs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLinhVucKinhDoanhs(LinhVucKinhDoanh linhVucKinhDoanh)
        {
            base.AddObject("LinhVucKinhDoanhs", linhVucKinhDoanh);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NhanViens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNhanViens(NhanVien nhanVien)
        {
            base.AddObject("NhanViens", nhanVien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QuocGias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuocGias(QuocGia quocGia)
        {
            base.AddObject("QuocGias", quocGia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TinhThanhs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTinhThanhs(TinhThanh tinhThanh)
        {
            base.AddObject("TinhThanhs", tinhThanh);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DanhMucNgoaiTes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDanhMucNgoaiTes(DanhMucNgoaiTe danhMucNgoaiTe)
        {
            base.AddObject("DanhMucNgoaiTes", danhMucNgoaiTe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NguoiLienHes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNguoiLienHes(NguoiLienHe nguoiLienHe)
        {
            base.AddObject("NguoiLienHes", nguoiLienHe);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticsModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        /// <param name="companyNameV">Initial value of the CompanyNameV property.</param>
        /// <param name="companyNameE">Initial value of the CompanyNameE property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="managementStaff">Initial value of the ManagementStaff property.</param>
        public static Customer CreateCustomer(global::System.String customerID, global::System.String companyNameV, global::System.String companyNameE, global::System.String phone, global::System.String managementStaff)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            customer.CompanyNameV = companyNameV;
            customer.CompanyNameE = companyNameE;
            customer.Phone = phone;
            customer.ManagementStaff = managementStaff;
            return customer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.String _CustomerID;
        partial void OnCustomerIDChanging(global::System.String value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyNameV
        {
            get
            {
                return _CompanyNameV;
            }
            set
            {
                OnCompanyNameVChanging(value);
                ReportPropertyChanging("CompanyNameV");
                _CompanyNameV = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CompanyNameV");
                OnCompanyNameVChanged();
            }
        }
        private global::System.String _CompanyNameV;
        partial void OnCompanyNameVChanging(global::System.String value);
        partial void OnCompanyNameVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyNameE
        {
            get
            {
                return _CompanyNameE;
            }
            set
            {
                OnCompanyNameEChanging(value);
                ReportPropertyChanging("CompanyNameE");
                _CompanyNameE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CompanyNameE");
                OnCompanyNameEChanged();
            }
        }
        private global::System.String _CompanyNameE;
        partial void OnCompanyNameEChanging(global::System.String value);
        partial void OnCompanyNameEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyNameS
        {
            get
            {
                return _CompanyNameS;
            }
            set
            {
                OnCompanyNameSChanging(value);
                ReportPropertyChanging("CompanyNameS");
                _CompanyNameS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyNameS");
                OnCompanyNameSChanged();
            }
        }
        private global::System.String _CompanyNameS;
        partial void OnCompanyNameSChanging(global::System.String value);
        partial void OnCompanyNameSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Business
        {
            get
            {
                return _Business;
            }
            set
            {
                OnBusinessChanging(value);
                ReportPropertyChanging("Business");
                _Business = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Business");
                OnBusinessChanged();
            }
        }
        private global::System.String _Business;
        partial void OnBusinessChanging(global::System.String value);
        partial void OnBusinessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Company
        {
            get
            {
                return _Company;
            }
            set
            {
                OnCompanyChanging(value);
                ReportPropertyChanging("Company");
                _Company = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Company");
                OnCompanyChanged();
            }
        }
        private global::System.String _Company;
        partial void OnCompanyChanging(global::System.String value);
        partial void OnCompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Classify
        {
            get
            {
                return _Classify;
            }
            set
            {
                OnClassifyChanging(value);
                ReportPropertyChanging("Classify");
                _Classify = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Classify");
                OnClassifyChanged();
            }
        }
        private global::System.String _Classify;
        partial void OnClassifyChanging(global::System.String value);
        partial void OnClassifyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NationalName
        {
            get
            {
                return _NationalName;
            }
            set
            {
                OnNationalNameChanging(value);
                ReportPropertyChanging("NationalName");
                _NationalName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NationalName");
                OnNationalNameChanged();
            }
        }
        private global::System.String _NationalName;
        partial void OnNationalNameChanging(global::System.String value);
        partial void OnNationalNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CityName
        {
            get
            {
                return _CityName;
            }
            set
            {
                OnCityNameChanging(value);
                ReportPropertyChanging("CityName");
                _CityName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CityName");
                OnCityNameChanged();
            }
        }
        private global::System.String _CityName;
        partial void OnCityNameChanging(global::System.String value);
        partial void OnCityNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private global::System.String _Fax;
        partial void OnFaxChanging(global::System.String value);
        partial void OnFaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Wed
        {
            get
            {
                return _Wed;
            }
            set
            {
                OnWedChanging(value);
                ReportPropertyChanging("Wed");
                _Wed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Wed");
                OnWedChanged();
            }
        }
        private global::System.String _Wed;
        partial void OnWedChanging(global::System.String value);
        partial void OnWedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ManagementStaff
        {
            get
            {
                return _ManagementStaff;
            }
            set
            {
                OnManagementStaffChanging(value);
                ReportPropertyChanging("ManagementStaff");
                _ManagementStaff = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ManagementStaff");
                OnManagementStaffChanged();
            }
        }
        private global::System.String _ManagementStaff;
        partial void OnManagementStaffChanging(global::System.String value);
        partial void OnManagementStaffChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticsModel", Name="DanhMucNgoaiTe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DanhMucNgoaiTe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DanhMucNgoaiTe object.
        /// </summary>
        /// <param name="maNgoaiTe">Initial value of the MaNgoaiTe property.</param>
        public static DanhMucNgoaiTe CreateDanhMucNgoaiTe(global::System.String maNgoaiTe)
        {
            DanhMucNgoaiTe danhMucNgoaiTe = new DanhMucNgoaiTe();
            danhMucNgoaiTe.MaNgoaiTe = maNgoaiTe;
            return danhMucNgoaiTe;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaNgoaiTe
        {
            get
            {
                return _MaNgoaiTe;
            }
            set
            {
                if (_MaNgoaiTe != value)
                {
                    OnMaNgoaiTeChanging(value);
                    ReportPropertyChanging("MaNgoaiTe");
                    _MaNgoaiTe = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaNgoaiTe");
                    OnMaNgoaiTeChanged();
                }
            }
        }
        private global::System.String _MaNgoaiTe;
        partial void OnMaNgoaiTeChanging(global::System.String value);
        partial void OnMaNgoaiTeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenNgoaiTe
        {
            get
            {
                return _TenNgoaiTe;
            }
            set
            {
                OnTenNgoaiTeChanging(value);
                ReportPropertyChanging("TenNgoaiTe");
                _TenNgoaiTe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenNgoaiTe");
                OnTenNgoaiTeChanged();
            }
        }
        private global::System.String _TenNgoaiTe;
        partial void OnTenNgoaiTeChanging(global::System.String value);
        partial void OnTenNgoaiTeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GhiChu
        {
            get
            {
                return _GhiChu;
            }
            set
            {
                OnGhiChuChanging(value);
                ReportPropertyChanging("GhiChu");
                _GhiChu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GhiChu");
                OnGhiChuChanged();
            }
        }
        private global::System.String _GhiChu;
        partial void OnGhiChuChanging(global::System.String value);
        partial void OnGhiChuChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticsModel", Name="LinhVucKinhDoanh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LinhVucKinhDoanh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LinhVucKinhDoanh object.
        /// </summary>
        /// <param name="maLinhVuc">Initial value of the MaLinhVuc property.</param>
        public static LinhVucKinhDoanh CreateLinhVucKinhDoanh(global::System.Int32 maLinhVuc)
        {
            LinhVucKinhDoanh linhVucKinhDoanh = new LinhVucKinhDoanh();
            linhVucKinhDoanh.MaLinhVuc = maLinhVuc;
            return linhVucKinhDoanh;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaLinhVuc
        {
            get
            {
                return _MaLinhVuc;
            }
            set
            {
                if (_MaLinhVuc != value)
                {
                    OnMaLinhVucChanging(value);
                    ReportPropertyChanging("MaLinhVuc");
                    _MaLinhVuc = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaLinhVuc");
                    OnMaLinhVucChanged();
                }
            }
        }
        private global::System.Int32 _MaLinhVuc;
        partial void OnMaLinhVucChanging(global::System.Int32 value);
        partial void OnMaLinhVucChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenLinhVuc
        {
            get
            {
                return _TenLinhVuc;
            }
            set
            {
                OnTenLinhVucChanging(value);
                ReportPropertyChanging("TenLinhVuc");
                _TenLinhVuc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenLinhVuc");
                OnTenLinhVucChanged();
            }
        }
        private global::System.String _TenLinhVuc;
        partial void OnTenLinhVucChanging(global::System.String value);
        partial void OnTenLinhVucChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GhiChu
        {
            get
            {
                return _GhiChu;
            }
            set
            {
                OnGhiChuChanging(value);
                ReportPropertyChanging("GhiChu");
                _GhiChu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GhiChu");
                OnGhiChuChanged();
            }
        }
        private global::System.String _GhiChu;
        partial void OnGhiChuChanging(global::System.String value);
        partial void OnGhiChuChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticsModel", Name="NguoiLienHe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NguoiLienHe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NguoiLienHe object.
        /// </summary>
        /// <param name="maNLH">Initial value of the MaNLH property.</param>
        public static NguoiLienHe CreateNguoiLienHe(global::System.String maNLH)
        {
            NguoiLienHe nguoiLienHe = new NguoiLienHe();
            nguoiLienHe.MaNLH = maNLH;
            return nguoiLienHe;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaNLH
        {
            get
            {
                return _MaNLH;
            }
            set
            {
                if (_MaNLH != value)
                {
                    OnMaNLHChanging(value);
                    ReportPropertyChanging("MaNLH");
                    _MaNLH = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaNLH");
                    OnMaNLHChanged();
                }
            }
        }
        private global::System.String _MaNLH;
        partial void OnMaNLHChanging(global::System.String value);
        partial void OnMaNLHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoVaChuLotNLH
        {
            get
            {
                return _HoVaChuLotNLH;
            }
            set
            {
                OnHoVaChuLotNLHChanging(value);
                ReportPropertyChanging("HoVaChuLotNLH");
                _HoVaChuLotNLH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HoVaChuLotNLH");
                OnHoVaChuLotNLHChanged();
            }
        }
        private global::System.String _HoVaChuLotNLH;
        partial void OnHoVaChuLotNLHChanging(global::System.String value);
        partial void OnHoVaChuLotNLHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenNLH
        {
            get
            {
                return _TenNLH;
            }
            set
            {
                OnTenNLHChanging(value);
                ReportPropertyChanging("TenNLH");
                _TenNLH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenNLH");
                OnTenNLHChanged();
            }
        }
        private global::System.String _TenNLH;
        partial void OnTenNLHChanging(global::System.String value);
        partial void OnTenNLHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhongBan
        {
            get
            {
                return _PhongBan;
            }
            set
            {
                OnPhongBanChanging(value);
                ReportPropertyChanging("PhongBan");
                _PhongBan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhongBan");
                OnPhongBanChanged();
            }
        }
        private global::System.String _PhongBan;
        partial void OnPhongBanChanging(global::System.String value);
        partial void OnPhongBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ChucDanh
        {
            get
            {
                return _ChucDanh;
            }
            set
            {
                OnChucDanhChanging(value);
                ReportPropertyChanging("ChucDanh");
                _ChucDanh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ChucDanh");
                OnChucDanhChanged();
            }
        }
        private global::System.String _ChucDanh;
        partial void OnChucDanhChanging(global::System.String value);
        partial void OnChucDanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SDT
        {
            get
            {
                return _SDT;
            }
            set
            {
                OnSDTChanging(value);
                ReportPropertyChanging("SDT");
                _SDT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SDT");
                OnSDTChanged();
            }
        }
        private global::System.String _SDT;
        partial void OnSDTChanging(global::System.String value);
        partial void OnSDTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SDT_DD
        {
            get
            {
                return _SDT_DD;
            }
            set
            {
                OnSDT_DDChanging(value);
                ReportPropertyChanging("SDT_DD");
                _SDT_DD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SDT_DD");
                OnSDT_DDChanged();
            }
        }
        private global::System.String _SDT_DD;
        partial void OnSDT_DDChanging(global::System.String value);
        partial void OnSDT_DDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticsModel", Name="NhanVien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NhanVien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NhanVien object.
        /// </summary>
        /// <param name="maNhanVien">Initial value of the MaNhanVien property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="nickName">Initial value of the NickName property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="birthday">Initial value of the Birthday property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static NhanVien CreateNhanVien(global::System.Int32 maNhanVien, global::System.String firstName, global::System.String lastName, global::System.String nickName, global::System.Double gender, global::System.String address, global::System.String birthday, global::System.String email, global::System.String username, global::System.String password)
        {
            NhanVien nhanVien = new NhanVien();
            nhanVien.MaNhanVien = maNhanVien;
            nhanVien.FirstName = firstName;
            nhanVien.LastName = lastName;
            nhanVien.NickName = nickName;
            nhanVien.Gender = gender;
            nhanVien.Address = address;
            nhanVien.Birthday = birthday;
            nhanVien.Email = email;
            nhanVien.Username = username;
            nhanVien.Password = password;
            return nhanVien;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaNhanVien
        {
            get
            {
                return _MaNhanVien;
            }
            set
            {
                if (_MaNhanVien != value)
                {
                    OnMaNhanVienChanging(value);
                    ReportPropertyChanging("MaNhanVien");
                    _MaNhanVien = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaNhanVien");
                    OnMaNhanVienChanged();
                }
            }
        }
        private global::System.Int32 _MaNhanVien;
        partial void OnMaNhanVienChanging(global::System.Int32 value);
        partial void OnMaNhanVienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NickName
        {
            get
            {
                return _NickName;
            }
            set
            {
                OnNickNameChanging(value);
                ReportPropertyChanging("NickName");
                _NickName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NickName");
                OnNickNameChanged();
            }
        }
        private global::System.String _NickName;
        partial void OnNickNameChanging(global::System.String value);
        partial void OnNickNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.Double _Gender;
        partial void OnGenderChanging(global::System.Double value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Birthday
        {
            get
            {
                return _Birthday;
            }
            set
            {
                OnBirthdayChanging(value);
                ReportPropertyChanging("Birthday");
                _Birthday = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Birthday");
                OnBirthdayChanged();
            }
        }
        private global::System.String _Birthday;
        partial void OnBirthdayChanging(global::System.String value);
        partial void OnBirthdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Department
        {
            get
            {
                return _Department;
            }
            set
            {
                OnDepartmentChanging(value);
                ReportPropertyChanging("Department");
                _Department = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Department");
                OnDepartmentChanged();
            }
        }
        private global::System.String _Department;
        partial void OnDepartmentChanging(global::System.String value);
        partial void OnDepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticsModel", Name="QuocGia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QuocGia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QuocGia object.
        /// </summary>
        /// <param name="maQuocGia">Initial value of the MaQuocGia property.</param>
        /// <param name="tenQuocGia">Initial value of the TenQuocGia property.</param>
        public static QuocGia CreateQuocGia(global::System.String maQuocGia, global::System.String tenQuocGia)
        {
            QuocGia quocGia = new QuocGia();
            quocGia.MaQuocGia = maQuocGia;
            quocGia.TenQuocGia = tenQuocGia;
            return quocGia;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaQuocGia
        {
            get
            {
                return _MaQuocGia;
            }
            set
            {
                if (_MaQuocGia != value)
                {
                    OnMaQuocGiaChanging(value);
                    ReportPropertyChanging("MaQuocGia");
                    _MaQuocGia = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaQuocGia");
                    OnMaQuocGiaChanged();
                }
            }
        }
        private global::System.String _MaQuocGia;
        partial void OnMaQuocGiaChanging(global::System.String value);
        partial void OnMaQuocGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenQuocGia
        {
            get
            {
                return _TenQuocGia;
            }
            set
            {
                if (_TenQuocGia != value)
                {
                    OnTenQuocGiaChanging(value);
                    ReportPropertyChanging("TenQuocGia");
                    _TenQuocGia = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TenQuocGia");
                    OnTenQuocGiaChanged();
                }
            }
        }
        private global::System.String _TenQuocGia;
        partial void OnTenQuocGiaChanging(global::System.String value);
        partial void OnTenQuocGiaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ABCLogisticsModel", Name="TinhThanh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TinhThanh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TinhThanh object.
        /// </summary>
        /// <param name="maTinhThanh">Initial value of the MaTinhThanh property.</param>
        /// <param name="tenTinhThanh">Initial value of the TenTinhThanh property.</param>
        public static TinhThanh CreateTinhThanh(global::System.String maTinhThanh, global::System.String tenTinhThanh)
        {
            TinhThanh tinhThanh = new TinhThanh();
            tinhThanh.MaTinhThanh = maTinhThanh;
            tinhThanh.TenTinhThanh = tenTinhThanh;
            return tinhThanh;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaTinhThanh
        {
            get
            {
                return _MaTinhThanh;
            }
            set
            {
                if (_MaTinhThanh != value)
                {
                    OnMaTinhThanhChanging(value);
                    ReportPropertyChanging("MaTinhThanh");
                    _MaTinhThanh = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaTinhThanh");
                    OnMaTinhThanhChanged();
                }
            }
        }
        private global::System.String _MaTinhThanh;
        partial void OnMaTinhThanhChanging(global::System.String value);
        partial void OnMaTinhThanhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenTinhThanh
        {
            get
            {
                return _TenTinhThanh;
            }
            set
            {
                if (_TenTinhThanh != value)
                {
                    OnTenTinhThanhChanging(value);
                    ReportPropertyChanging("TenTinhThanh");
                    _TenTinhThanh = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TenTinhThanh");
                    OnTenTinhThanhChanged();
                }
            }
        }
        private global::System.String _TenTinhThanh;
        partial void OnTenTinhThanhChanging(global::System.String value);
        partial void OnTenTinhThanhChanged();

        #endregion

    
    }

    #endregion

    
}
